### ISSUE TITLE
convert/prepare ALTLab database to import JSON format

### ISSUE THREAD

**Issue by dwhieb** [UAlbertaALTLab/crk-db#10]
Convert ALTLab's JSON database to import JSON format for itwêwina.

**Comment by eddieantonio** [comment]
So itwêwina uses Djagno's Object-Relational Mapper (ORM), which means the data is really "managed" by Django's model classes: see https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/blob/2985cd5391c9330819f037f7298d9a1cbcd8932f/CreeDictionary/API/models.py#L36

The fact that it's stored in SQLite3 is more-or-less an implementation detail rather than a requirement.

@UAlbertaALTLab/developers will need to discuss what database backing works best to store the hierarchical data.

**Comment by dwhieb** [comment]
Closed by 457fe06b3a794b750089b628501a94b5418e083e.
