### ISSUE TITLE
integrate Jeff Muehlbauer's morpheme list

### ISSUE THREAD

**Issue by dwhieb** [UAlbertaALTLab/crk-db#26]
Incorporate Jeff Muehlbauer's morpheme list.

LaTeX version lives here:
https://drive.google.com/drive/u/0/folders/0B3eCGz24iHRmTDhCSmdXclc1OFE

### Notes

* The LaTeX source file seems to have encoding issues. See whether the characters can be recovered, or whether we need to obtain another copy of the source.

**Comment by andrewdotn** [comment]
It’s macroman. On a linux machine you can do the conversion with:

    $ iconv -f macroman -t UTF-8 MorphemeDictionary.tex
    …
    \textit{M} = Muehlbauer, Jeffrey. \textit{kâ-yôskâtahk ôma nêhiyawêwin: The representation of intentionality in Plains Cree}. Ph.D. Thesis, The University of British Columbia. Vancouver, BC.\\\\
    …

That was a lucky guess on my part, but you can also try https://ftfy.now.sh for diagnosing encoding problems. On my mac, I can’t use that site for this file, because the mac seems to detect the encoding when the text goes onto the clipboard, so pasting it into my browser shows the ‘right’ encoding.

**Comment by fbanados** [comment]
Computationally, this issue means we would like to generate a toolbox file from the Muehlbauer list that can then be used to merge into importjson or for merging directly into CW.

Also from other lists shared by Arok

**Comment by fbanados** [comment]
Actually, duplicate from #28
