### ISSUE TITLE
generate slug for each entry

### ISSUE THREAD

**Issue by dwhieb** [UAlbertaALTLab/crk-db#40]
In some cases, itwêwina relies on search queries rather than URL parameters for routing. (I think this happens specifically with homographs?) It might be useful to generate a unique slug for each entry, allowing itwêwina to simplify routing-related code. Homographs would could get routed as `/atim1` and `/atim2`, for example.

The slug could be the same as the key, or it could be the full headword with diacritics + a homograph number if needed.

**Comment by dwhieb** [comment]
@andrewdotn Do you remember the specific cases where itwêwina relies on query strings for routing?

**Comment by eddieantonio** [comment]
It's in the homograph disambiguator!

https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/blob/8224633e03452b7058b8729619491ebcaf77068c/CreeDictionary/API/models.py#L107-L118

And yes, this would be would be _very_ helpful!

We'd like a URL like `/word/{headword}`. Because of the paradigms, I think it'd be best if headwords that are associated with different inflectional categories (and thus pardigms) are given different disambiguations. 

itwêwina _should_ store headwords separate from ALL WORD FORMS, but it doesn't, so it needs a little help with, e.g., non-lemma wordforms that have their own definition(s):

Compare:
 - https://itwewina.altlab.app/word/nan%C3%A2skom%C3%AAw/
 - https://itwewina.altlab.app/word/kinan%C3%A2skomitin/?pos=IPC

**Comment by dwhieb** [comment]
Closed by 457fe06b3a794b750089b628501a94b5418e083e.
